// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.3
// source: testdemo.proto

package testdemo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTagReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetTagReq) Reset() {
	*x = GetTagReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testdemo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTagReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTagReq) ProtoMessage() {}

func (x *GetTagReq) ProtoReflect() protoreflect.Message {
	mi := &file_testdemo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTagReq.ProtoReflect.Descriptor instead.
func (*GetTagReq) Descriptor() ([]byte, []int) {
	return file_testdemo_proto_rawDescGZIP(), []int{0}
}

func (x *GetTagReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetTagRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Meta *MetaRes `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Data *TagData `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetTagRes) Reset() {
	*x = GetTagRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testdemo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTagRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTagRes) ProtoMessage() {}

func (x *GetTagRes) ProtoReflect() protoreflect.Message {
	mi := &file_testdemo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTagRes.ProtoReflect.Descriptor instead.
func (*GetTagRes) Descriptor() ([]byte, []int) {
	return file_testdemo_proto_rawDescGZIP(), []int{1}
}

func (x *GetTagRes) GetMeta() *MetaRes {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *GetTagRes) GetData() *TagData {
	if x != nil {
		return x.Data
	}
	return nil
}

type DelTagReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Operator *Operator `protobuf:"bytes,2,opt,name=operator,proto3" json:"operator,omitempty"` //validate:"required=false",comment:"操作人，网关注入"
}

func (x *DelTagReq) Reset() {
	*x = DelTagReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testdemo_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelTagReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelTagReq) ProtoMessage() {}

func (x *DelTagReq) ProtoReflect() protoreflect.Message {
	mi := &file_testdemo_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelTagReq.ProtoReflect.Descriptor instead.
func (*DelTagReq) Descriptor() ([]byte, []int) {
	return file_testdemo_proto_rawDescGZIP(), []int{2}
}

func (x *DelTagReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DelTagReq) GetOperator() *Operator {
	if x != nil {
		return x.Operator
	}
	return nil
}

type DelTagRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Meta *MetaRes `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
}

func (x *DelTagRes) Reset() {
	*x = DelTagRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testdemo_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelTagRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelTagRes) ProtoMessage() {}

func (x *DelTagRes) ProtoReflect() protoreflect.Message {
	mi := &file_testdemo_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelTagRes.ProtoReflect.Descriptor instead.
func (*DelTagRes) Descriptor() ([]byte, []int) {
	return file_testdemo_proto_rawDescGZIP(), []int{3}
}

func (x *DelTagRes) GetMeta() *MetaRes {
	if x != nil {
		return x.Meta
	}
	return nil
}

type GetTagListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page     string    `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize string    `protobuf:"bytes,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	Operator *Operator `protobuf:"bytes,3,opt,name=operator,proto3" json:"operator,omitempty"` //validate:"required=false",comment:"操作人，网关注入"
}

func (x *GetTagListReq) Reset() {
	*x = GetTagListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testdemo_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTagListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTagListReq) ProtoMessage() {}

func (x *GetTagListReq) ProtoReflect() protoreflect.Message {
	mi := &file_testdemo_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTagListReq.ProtoReflect.Descriptor instead.
func (*GetTagListReq) Descriptor() ([]byte, []int) {
	return file_testdemo_proto_rawDescGZIP(), []int{4}
}

func (x *GetTagListReq) GetPage() string {
	if x != nil {
		return x.Page
	}
	return ""
}

func (x *GetTagListReq) GetPageSize() string {
	if x != nil {
		return x.PageSize
	}
	return ""
}

func (x *GetTagListReq) GetOperator() *Operator {
	if x != nil {
		return x.Operator
	}
	return nil
}

type GetTagListRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Meta *MetaRes        `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Data *GetTagListData `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetTagListRes) Reset() {
	*x = GetTagListRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testdemo_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTagListRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTagListRes) ProtoMessage() {}

func (x *GetTagListRes) ProtoReflect() protoreflect.Message {
	mi := &file_testdemo_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTagListRes.ProtoReflect.Descriptor instead.
func (*GetTagListRes) Descriptor() ([]byte, []int) {
	return file_testdemo_proto_rawDescGZIP(), []int{5}
}

func (x *GetTagListRes) GetMeta() *MetaRes {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *GetTagListRes) GetData() *GetTagListData {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetTagListData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PageInfo *PageInfo  `protobuf:"bytes,1,opt,name=pageInfo,proto3" json:"pageInfo,omitempty"`
	List     []*TagData `protobuf:"bytes,4,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *GetTagListData) Reset() {
	*x = GetTagListData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testdemo_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTagListData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTagListData) ProtoMessage() {}

func (x *GetTagListData) ProtoReflect() protoreflect.Message {
	mi := &file_testdemo_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTagListData.ProtoReflect.Descriptor instead.
func (*GetTagListData) Descriptor() ([]byte, []int) {
	return file_testdemo_proto_rawDescGZIP(), []int{6}
}

func (x *GetTagListData) GetPageInfo() *PageInfo {
	if x != nil {
		return x.PageInfo
	}
	return nil
}

func (x *GetTagListData) GetList() []*TagData {
	if x != nil {
		return x.List
	}
	return nil
}

type EditTagReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Operator  *Operator `protobuf:"bytes,1,opt,name=operator,proto3" json:"operator,omitempty"`   //validate:"required=false",comment:"操作人，网关注入"
	Id        string    `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`               //validate:"required=true"
	ChannelId string    `protobuf:"bytes,3,opt,name=channelId,proto3" json:"channelId,omitempty"` //validate:"required=true",comment:"渠道id"
	Name      string    `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`           //validate:"required=true",comment:"标签名称"
	DeletedAt string    `protobuf:"bytes,5,opt,name=deletedAt,proto3" json:"deletedAt,omitempty"` //validate:"required=true",comment:"删除时间"
	CreatedAt string    `protobuf:"bytes,6,opt,name=createdAt,proto3" json:"createdAt,omitempty"` //validate:"required=true",comment:"创建时间"
	UpdatedAt string    `protobuf:"bytes,7,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"` //validate:"required=true",comment:"更新时间"
}

func (x *EditTagReq) Reset() {
	*x = EditTagReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testdemo_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EditTagReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditTagReq) ProtoMessage() {}

func (x *EditTagReq) ProtoReflect() protoreflect.Message {
	mi := &file_testdemo_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditTagReq.ProtoReflect.Descriptor instead.
func (*EditTagReq) Descriptor() ([]byte, []int) {
	return file_testdemo_proto_rawDescGZIP(), []int{7}
}

func (x *EditTagReq) GetOperator() *Operator {
	if x != nil {
		return x.Operator
	}
	return nil
}

func (x *EditTagReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EditTagReq) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *EditTagReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EditTagReq) GetDeletedAt() string {
	if x != nil {
		return x.DeletedAt
	}
	return ""
}

func (x *EditTagReq) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *EditTagReq) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type EditTagRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Meta *MetaRes `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Data *TagData `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *EditTagRes) Reset() {
	*x = EditTagRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testdemo_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EditTagRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditTagRes) ProtoMessage() {}

func (x *EditTagRes) ProtoReflect() protoreflect.Message {
	mi := &file_testdemo_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditTagRes.ProtoReflect.Descriptor instead.
func (*EditTagRes) Descriptor() ([]byte, []int) {
	return file_testdemo_proto_rawDescGZIP(), []int{8}
}

func (x *EditTagRes) GetMeta() *MetaRes {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *EditTagRes) GetData() *TagData {
	if x != nil {
		return x.Data
	}
	return nil
}

type TagData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ChannelId string `protobuf:"bytes,2,opt,name=channelId,proto3" json:"channelId,omitempty"` //comment:"渠道id"
	Name      string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`           //comment:"标签名称"
	DeletedAt string `protobuf:"bytes,4,opt,name=deletedAt,proto3" json:"deletedAt,omitempty"` //comment:"删除时间"
	CreatedAt string `protobuf:"bytes,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"` //comment:"创建时间"
	UpdatedAt string `protobuf:"bytes,6,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"` //comment:"更新时间"
}

func (x *TagData) Reset() {
	*x = TagData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testdemo_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TagData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagData) ProtoMessage() {}

func (x *TagData) ProtoReflect() protoreflect.Message {
	mi := &file_testdemo_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagData.ProtoReflect.Descriptor instead.
func (*TagData) Descriptor() ([]byte, []int) {
	return file_testdemo_proto_rawDescGZIP(), []int{9}
}

func (x *TagData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TagData) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *TagData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TagData) GetDeletedAt() string {
	if x != nil {
		return x.DeletedAt
	}
	return ""
}

func (x *TagData) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *TagData) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type Operator struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsSuper   bool   `protobuf:"varint,1,opt,name=isSuper,proto3" json:"isSuper,omitempty"`
	UserId    string `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Mobile    string `protobuf:"bytes,3,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Name      string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	OrgId     string `protobuf:"bytes,5,opt,name=orgId,proto3" json:"orgId,omitempty"`
	ChannelId string `protobuf:"bytes,6,opt,name=channelId,proto3" json:"channelId,omitempty"`
}

func (x *Operator) Reset() {
	*x = Operator{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testdemo_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Operator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Operator) ProtoMessage() {}

func (x *Operator) ProtoReflect() protoreflect.Message {
	mi := &file_testdemo_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Operator.ProtoReflect.Descriptor instead.
func (*Operator) Descriptor() ([]byte, []int) {
	return file_testdemo_proto_rawDescGZIP(), []int{10}
}

func (x *Operator) GetIsSuper() bool {
	if x != nil {
		return x.IsSuper
	}
	return false
}

func (x *Operator) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Operator) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *Operator) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Operator) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *Operator) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

type Marketer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsSuper   bool   `protobuf:"varint,1,opt,name=isSuper,proto3" json:"isSuper,omitempty"`
	UserId    string `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Name      string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Mobile    string `protobuf:"bytes,4,opt,name=mobile,proto3" json:"mobile,omitempty"`
	OrgId     string `protobuf:"bytes,5,opt,name=orgId,proto3" json:"orgId,omitempty"`
	ChannelId string `protobuf:"bytes,6,opt,name=channelId,proto3" json:"channelId,omitempty"`
}

func (x *Marketer) Reset() {
	*x = Marketer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testdemo_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Marketer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Marketer) ProtoMessage() {}

func (x *Marketer) ProtoReflect() protoreflect.Message {
	mi := &file_testdemo_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Marketer.ProtoReflect.Descriptor instead.
func (*Marketer) Descriptor() ([]byte, []int) {
	return file_testdemo_proto_rawDescGZIP(), []int{11}
}

func (x *Marketer) GetIsSuper() bool {
	if x != nil {
		return x.IsSuper
	}
	return false
}

func (x *Marketer) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Marketer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Marketer) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *Marketer) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *Marketer) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

type WxUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WxUnionId    string `protobuf:"bytes,1,opt,name=wxUnionId,proto3" json:"wxUnionId,omitempty"`
	WxMiniAppId  string `protobuf:"bytes,2,opt,name=wxMiniAppId,proto3" json:"wxMiniAppId,omitempty"`
	WxMiniOpenId string `protobuf:"bytes,3,opt,name=wxMiniOpenId,proto3" json:"wxMiniOpenId,omitempty"`
	WxNickname   string `protobuf:"bytes,4,opt,name=wxNickname,proto3" json:"wxNickname,omitempty"`
	WxAvatar     string `protobuf:"bytes,5,opt,name=wxAvatar,proto3" json:"wxAvatar,omitempty"`
	WxMobile     string `protobuf:"bytes,6,opt,name=wxMobile,proto3" json:"wxMobile,omitempty"`
	RealName     string `protobuf:"bytes,7,opt,name=realName,proto3" json:"realName,omitempty"`
}

func (x *WxUser) Reset() {
	*x = WxUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testdemo_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WxUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WxUser) ProtoMessage() {}

func (x *WxUser) ProtoReflect() protoreflect.Message {
	mi := &file_testdemo_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WxUser.ProtoReflect.Descriptor instead.
func (*WxUser) Descriptor() ([]byte, []int) {
	return file_testdemo_proto_rawDescGZIP(), []int{12}
}

func (x *WxUser) GetWxUnionId() string {
	if x != nil {
		return x.WxUnionId
	}
	return ""
}

func (x *WxUser) GetWxMiniAppId() string {
	if x != nil {
		return x.WxMiniAppId
	}
	return ""
}

func (x *WxUser) GetWxMiniOpenId() string {
	if x != nil {
		return x.WxMiniOpenId
	}
	return ""
}

func (x *WxUser) GetWxNickname() string {
	if x != nil {
		return x.WxNickname
	}
	return ""
}

func (x *WxUser) GetWxAvatar() string {
	if x != nil {
		return x.WxAvatar
	}
	return ""
}

func (x *WxUser) GetWxMobile() string {
	if x != nil {
		return x.WxMobile
	}
	return ""
}

func (x *WxUser) GetRealName() string {
	if x != nil {
		return x.RealName
	}
	return ""
}

type MemberUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserMobile   string `protobuf:"bytes,1,opt,name=userMobile,proto3" json:"userMobile,omitempty"`
	UserName     string `protobuf:"bytes,2,opt,name=userName,proto3" json:"userName,omitempty"`
	UserIdentity string `protobuf:"bytes,3,opt,name=userIdentity,proto3" json:"userIdentity,omitempty"`
	UserAddress  string `protobuf:"bytes,4,opt,name=userAddress,proto3" json:"userAddress,omitempty"`
	UserProvince string `protobuf:"bytes,5,opt,name=userProvince,proto3" json:"userProvince,omitempty"`
	UserCity     string `protobuf:"bytes,6,opt,name=userCity,proto3" json:"userCity,omitempty"`
	UserDistrict string `protobuf:"bytes,7,opt,name=userDistrict,proto3" json:"userDistrict,omitempty"`
}

func (x *MemberUser) Reset() {
	*x = MemberUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testdemo_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MemberUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberUser) ProtoMessage() {}

func (x *MemberUser) ProtoReflect() protoreflect.Message {
	mi := &file_testdemo_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberUser.ProtoReflect.Descriptor instead.
func (*MemberUser) Descriptor() ([]byte, []int) {
	return file_testdemo_proto_rawDescGZIP(), []int{13}
}

func (x *MemberUser) GetUserMobile() string {
	if x != nil {
		return x.UserMobile
	}
	return ""
}

func (x *MemberUser) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *MemberUser) GetUserIdentity() string {
	if x != nil {
		return x.UserIdentity
	}
	return ""
}

func (x *MemberUser) GetUserAddress() string {
	if x != nil {
		return x.UserAddress
	}
	return ""
}

func (x *MemberUser) GetUserProvince() string {
	if x != nil {
		return x.UserProvince
	}
	return ""
}

func (x *MemberUser) GetUserCity() string {
	if x != nil {
		return x.UserCity
	}
	return ""
}

func (x *MemberUser) GetUserDistrict() string {
	if x != nil {
		return x.UserDistrict
	}
	return ""
}

type PageInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page      string `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize  string `protobuf:"bytes,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	TotalPage string `protobuf:"bytes,3,opt,name=totalPage,proto3" json:"totalPage,omitempty"`
	Total     string `protobuf:"bytes,4,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *PageInfo) Reset() {
	*x = PageInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testdemo_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageInfo) ProtoMessage() {}

func (x *PageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_testdemo_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageInfo.ProtoReflect.Descriptor instead.
func (*PageInfo) Descriptor() ([]byte, []int) {
	return file_testdemo_proto_rawDescGZIP(), []int{14}
}

func (x *PageInfo) GetPage() string {
	if x != nil {
		return x.Page
	}
	return ""
}

func (x *PageInfo) GetPageSize() string {
	if x != nil {
		return x.PageSize
	}
	return ""
}

func (x *PageInfo) GetTotalPage() string {
	if x != nil {
		return x.TotalPage
	}
	return ""
}

func (x *PageInfo) GetTotal() string {
	if x != nil {
		return x.Total
	}
	return ""
}

type ImageData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Url  string `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *ImageData) Reset() {
	*x = ImageData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testdemo_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImageData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageData) ProtoMessage() {}

func (x *ImageData) ProtoReflect() protoreflect.Message {
	mi := &file_testdemo_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageData.ProtoReflect.Descriptor instead.
func (*ImageData) Descriptor() ([]byte, []int) {
	return file_testdemo_proto_rawDescGZIP(), []int{15}
}

func (x *ImageData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ImageData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ImageData) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type PingReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PingReq) Reset() {
	*x = PingReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testdemo_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingReq) ProtoMessage() {}

func (x *PingReq) ProtoReflect() protoreflect.Message {
	mi := &file_testdemo_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingReq.ProtoReflect.Descriptor instead.
func (*PingReq) Descriptor() ([]byte, []int) {
	return file_testdemo_proto_rawDescGZIP(), []int{16}
}

type PingRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Meta *MetaRes `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
}

func (x *PingRes) Reset() {
	*x = PingRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testdemo_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRes) ProtoMessage() {}

func (x *PingRes) ProtoReflect() protoreflect.Message {
	mi := &file_testdemo_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRes.ProtoReflect.Descriptor instead.
func (*PingRes) Descriptor() ([]byte, []int) {
	return file_testdemo_proto_rawDescGZIP(), []int{17}
}

func (x *PingRes) GetMeta() *MetaRes {
	if x != nil {
		return x.Meta
	}
	return nil
}

type MetaRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestId string `protobuf:"bytes,1,opt,name=requestId,proto3" json:"requestId,omitempty"`
	Code      int32  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Msg       string `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *MetaRes) Reset() {
	*x = MetaRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testdemo_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetaRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaRes) ProtoMessage() {}

func (x *MetaRes) ProtoReflect() protoreflect.Message {
	mi := &file_testdemo_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaRes.ProtoReflect.Descriptor instead.
func (*MetaRes) Descriptor() ([]byte, []int) {
	return file_testdemo_proto_rawDescGZIP(), []int{18}
}

func (x *MetaRes) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *MetaRes) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *MetaRes) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_testdemo_proto protoreflect.FileDescriptor

var file_testdemo_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x74, 0x65, 0x73, 0x74, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x74, 0x65, 0x73, 0x74, 0x64, 0x65, 0x6d, 0x6f, 0x22, 0x1b, 0x0a, 0x09, 0x47, 0x65,
	0x74, 0x54, 0x61, 0x67, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x59, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x54, 0x61,
	0x67, 0x52, 0x65, 0x73, 0x12, 0x25, 0x0a, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x11, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x4d, 0x65,
	0x74, 0x61, 0x52, 0x65, 0x73, 0x52, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x12, 0x25, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x74, 0x65, 0x73, 0x74,
	0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x54, 0x61, 0x67, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x22, 0x4b, 0x0a, 0x09, 0x44, 0x65, 0x6c, 0x54, 0x61, 0x67, 0x52, 0x65, 0x71, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x2e, 0x0a, 0x08, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x4f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x08, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x22,
	0x32, 0x0a, 0x09, 0x44, 0x65, 0x6c, 0x54, 0x61, 0x67, 0x52, 0x65, 0x73, 0x12, 0x25, 0x0a, 0x04,
	0x6d, 0x65, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x74, 0x65, 0x73,
	0x74, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x65, 0x73, 0x52, 0x04, 0x6d,
	0x65, 0x74, 0x61, 0x22, 0x6f, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x54, 0x61, 0x67, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x67, 0x65,
	0x53, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65,
	0x53, 0x69, 0x7a, 0x65, 0x12, 0x2e, 0x0a, 0x08, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x64, 0x65, 0x6d,
	0x6f, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x08, 0x6f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x6f, 0x72, 0x22, 0x64, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x54, 0x61, 0x67, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x73, 0x12, 0x25, 0x0a, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x4d,
	0x65, 0x74, 0x61, 0x52, 0x65, 0x73, 0x52, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x12, 0x2c, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x74, 0x65, 0x73,
	0x74, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x61, 0x67, 0x4c, 0x69, 0x73, 0x74,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x67, 0x0a, 0x0e, 0x47, 0x65,
	0x74, 0x54, 0x61, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x2e, 0x0a, 0x08,
	0x70, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12,
	0x2e, 0x74, 0x65, 0x73, 0x74, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x25, 0x0a, 0x04,
	0x6c, 0x69, 0x73, 0x74, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x74, 0x65, 0x73,
	0x74, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x54, 0x61, 0x67, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x6c,
	0x69, 0x73, 0x74, 0x22, 0xd8, 0x01, 0x0a, 0x0a, 0x45, 0x64, 0x69, 0x74, 0x54, 0x61, 0x67, 0x52,
	0x65, 0x71, 0x12, 0x2e, 0x0a, 0x08, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x64, 0x65, 0x6d, 0x6f, 0x2e,
	0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x08, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74,
	0x6f, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x41,
	0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64,
	0x41, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74,
	0x12, 0x1c, 0x0a, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x5a,
	0x0a, 0x0a, 0x45, 0x64, 0x69, 0x74, 0x54, 0x61, 0x67, 0x52, 0x65, 0x73, 0x12, 0x25, 0x0a, 0x04,
	0x6d, 0x65, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x74, 0x65, 0x73,
	0x74, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x65, 0x73, 0x52, 0x04, 0x6d,
	0x65, 0x74, 0x61, 0x12, 0x25, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x54, 0x61, 0x67,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0xa5, 0x01, 0x0a, 0x07, 0x54,
	0x61, 0x67, 0x44, 0x61, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65,
	0x6c, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x68, 0x61, 0x6e, 0x6e,
	0x65, 0x6c, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x64, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x41, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x41, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41,
	0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64,
	0x41, 0x74, 0x22, 0x9c, 0x01, 0x0a, 0x08, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x12,
	0x18, 0x0a, 0x07, 0x69, 0x73, 0x53, 0x75, 0x70, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x07, 0x69, 0x73, 0x53, 0x75, 0x70, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x6f, 0x72, 0x67, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6f, 0x72,
	0x67, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x64,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49,
	0x64, 0x22, 0x9c, 0x01, 0x0a, 0x08, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x65, 0x72, 0x12, 0x18,
	0x0a, 0x07, 0x69, 0x73, 0x53, 0x75, 0x70, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x69, 0x73, 0x53, 0x75, 0x70, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x6f, 0x72, 0x67, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6f, 0x72, 0x67,
	0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x64, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x64,
	0x22, 0xe0, 0x01, 0x0a, 0x06, 0x57, 0x78, 0x55, 0x73, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x77,
	0x78, 0x55, 0x6e, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x77, 0x78, 0x55, 0x6e, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x77, 0x78, 0x4d,
	0x69, 0x6e, 0x69, 0x41, 0x70, 0x70, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x77, 0x78, 0x4d, 0x69, 0x6e, 0x69, 0x41, 0x70, 0x70, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x77,
	0x78, 0x4d, 0x69, 0x6e, 0x69, 0x4f, 0x70, 0x65, 0x6e, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x77, 0x78, 0x4d, 0x69, 0x6e, 0x69, 0x4f, 0x70, 0x65, 0x6e, 0x49, 0x64, 0x12,
	0x1e, 0x0a, 0x0a, 0x77, 0x78, 0x4e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x77, 0x78, 0x4e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x77, 0x78, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x77, 0x78, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x77,
	0x78, 0x4d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x77,
	0x78, 0x4d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x61, 0x6c, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x61, 0x6c, 0x4e,
	0x61, 0x6d, 0x65, 0x22, 0xf2, 0x01, 0x0a, 0x0a, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x55, 0x73,
	0x65, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x4d, 0x6f, 0x62, 0x69, 0x6c, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x4d, 0x6f, 0x62, 0x69,
	0x6c, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x22,
	0x0a, 0x0c, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x75, 0x73, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x75, 0x73, 0x65, 0x72, 0x41, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x12, 0x22, 0x0a, 0x0c, 0x75, 0x73, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x76,
	0x69, 0x6e, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x75, 0x73, 0x65, 0x72,
	0x50, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72,
	0x43, 0x69, 0x74, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72,
	0x43, 0x69, 0x74, 0x79, 0x12, 0x22, 0x0a, 0x0c, 0x75, 0x73, 0x65, 0x72, 0x44, 0x69, 0x73, 0x74,
	0x72, 0x69, 0x63, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x75, 0x73, 0x65, 0x72,
	0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x63, 0x74, 0x22, 0x6e, 0x0a, 0x08, 0x50, 0x61, 0x67, 0x65,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x67, 0x65,
	0x53, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65,
	0x53, 0x69, 0x7a, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x50, 0x61, 0x67,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x50, 0x61,
	0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x22, 0x41, 0x0a, 0x09, 0x49, 0x6d, 0x61, 0x67,
	0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x22, 0x09, 0x0a, 0x07, 0x50,
	0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x22, 0x30, 0x0a, 0x07, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65,
	0x73, 0x12, 0x25, 0x0a, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x11, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x52,
	0x65, 0x73, 0x52, 0x04, 0x6d, 0x65, 0x74, 0x61, 0x22, 0x4d, 0x0a, 0x07, 0x4d, 0x65, 0x74, 0x61,
	0x52, 0x65, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x32, 0x9f, 0x02, 0x0a, 0x08, 0x54, 0x65, 0x73, 0x74,
	0x64, 0x65, 0x6d, 0x6f, 0x12, 0x2e, 0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x11, 0x2e, 0x74,
	0x65, 0x73, 0x74, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x1a,
	0x11, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x52,
	0x65, 0x73, 0x22, 0x00, 0x12, 0x37, 0x0a, 0x07, 0x45, 0x64, 0x69, 0x74, 0x54, 0x61, 0x67, 0x12,
	0x14, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x45, 0x64, 0x69, 0x74, 0x54,
	0x61, 0x67, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x64, 0x65, 0x6d, 0x6f,
	0x2e, 0x45, 0x64, 0x69, 0x74, 0x54, 0x61, 0x67, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x3a, 0x0a,
	0x0c, 0x47, 0x65, 0x74, 0x54, 0x61, 0x67, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x13, 0x2e,
	0x74, 0x65, 0x73, 0x74, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x61, 0x67, 0x52,
	0x65, 0x71, 0x1a, 0x13, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x47, 0x65,
	0x74, 0x54, 0x61, 0x67, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x34, 0x0a, 0x06, 0x44, 0x65, 0x6c,
	0x54, 0x61, 0x67, 0x12, 0x13, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x44,
	0x65, 0x6c, 0x54, 0x61, 0x67, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x64,
	0x65, 0x6d, 0x6f, 0x2e, 0x44, 0x65, 0x6c, 0x54, 0x61, 0x67, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12,
	0x38, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x54, 0x61, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x13, 0x2e,
	0x74, 0x65, 0x73, 0x74, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x61, 0x67, 0x52,
	0x65, 0x71, 0x1a, 0x13, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x47, 0x65,
	0x74, 0x54, 0x61, 0x67, 0x52, 0x65, 0x73, 0x22, 0x00, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f, 0x74,
	0x65, 0x73, 0x74, 0x64, 0x65, 0x6d, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_testdemo_proto_rawDescOnce sync.Once
	file_testdemo_proto_rawDescData = file_testdemo_proto_rawDesc
)

func file_testdemo_proto_rawDescGZIP() []byte {
	file_testdemo_proto_rawDescOnce.Do(func() {
		file_testdemo_proto_rawDescData = protoimpl.X.CompressGZIP(file_testdemo_proto_rawDescData)
	})
	return file_testdemo_proto_rawDescData
}

var file_testdemo_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_testdemo_proto_goTypes = []interface{}{
	(*GetTagReq)(nil),      // 0: testdemo.GetTagReq
	(*GetTagRes)(nil),      // 1: testdemo.GetTagRes
	(*DelTagReq)(nil),      // 2: testdemo.DelTagReq
	(*DelTagRes)(nil),      // 3: testdemo.DelTagRes
	(*GetTagListReq)(nil),  // 4: testdemo.GetTagListReq
	(*GetTagListRes)(nil),  // 5: testdemo.GetTagListRes
	(*GetTagListData)(nil), // 6: testdemo.GetTagListData
	(*EditTagReq)(nil),     // 7: testdemo.EditTagReq
	(*EditTagRes)(nil),     // 8: testdemo.EditTagRes
	(*TagData)(nil),        // 9: testdemo.TagData
	(*Operator)(nil),       // 10: testdemo.Operator
	(*Marketer)(nil),       // 11: testdemo.Marketer
	(*WxUser)(nil),         // 12: testdemo.WxUser
	(*MemberUser)(nil),     // 13: testdemo.MemberUser
	(*PageInfo)(nil),       // 14: testdemo.PageInfo
	(*ImageData)(nil),      // 15: testdemo.ImageData
	(*PingReq)(nil),        // 16: testdemo.PingReq
	(*PingRes)(nil),        // 17: testdemo.PingRes
	(*MetaRes)(nil),        // 18: testdemo.MetaRes
}
var file_testdemo_proto_depIdxs = []int32{
	18, // 0: testdemo.GetTagRes.meta:type_name -> testdemo.MetaRes
	9,  // 1: testdemo.GetTagRes.data:type_name -> testdemo.TagData
	10, // 2: testdemo.DelTagReq.operator:type_name -> testdemo.Operator
	18, // 3: testdemo.DelTagRes.meta:type_name -> testdemo.MetaRes
	10, // 4: testdemo.GetTagListReq.operator:type_name -> testdemo.Operator
	18, // 5: testdemo.GetTagListRes.meta:type_name -> testdemo.MetaRes
	6,  // 6: testdemo.GetTagListRes.data:type_name -> testdemo.GetTagListData
	14, // 7: testdemo.GetTagListData.pageInfo:type_name -> testdemo.PageInfo
	9,  // 8: testdemo.GetTagListData.list:type_name -> testdemo.TagData
	10, // 9: testdemo.EditTagReq.operator:type_name -> testdemo.Operator
	18, // 10: testdemo.EditTagRes.meta:type_name -> testdemo.MetaRes
	9,  // 11: testdemo.EditTagRes.data:type_name -> testdemo.TagData
	18, // 12: testdemo.PingRes.meta:type_name -> testdemo.MetaRes
	16, // 13: testdemo.Testdemo.Ping:input_type -> testdemo.PingReq
	7,  // 14: testdemo.Testdemo.EditTag:input_type -> testdemo.EditTagReq
	0,  // 15: testdemo.Testdemo.GetTagDetail:input_type -> testdemo.GetTagReq
	2,  // 16: testdemo.Testdemo.DelTag:input_type -> testdemo.DelTagReq
	0,  // 17: testdemo.Testdemo.GetTagList:input_type -> testdemo.GetTagReq
	17, // 18: testdemo.Testdemo.Ping:output_type -> testdemo.PingRes
	8,  // 19: testdemo.Testdemo.EditTag:output_type -> testdemo.EditTagRes
	1,  // 20: testdemo.Testdemo.GetTagDetail:output_type -> testdemo.GetTagRes
	3,  // 21: testdemo.Testdemo.DelTag:output_type -> testdemo.DelTagRes
	1,  // 22: testdemo.Testdemo.GetTagList:output_type -> testdemo.GetTagRes
	18, // [18:23] is the sub-list for method output_type
	13, // [13:18] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_testdemo_proto_init() }
func file_testdemo_proto_init() {
	if File_testdemo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_testdemo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTagReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_testdemo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTagRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_testdemo_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelTagReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_testdemo_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelTagRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_testdemo_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTagListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_testdemo_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTagListRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_testdemo_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTagListData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_testdemo_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EditTagReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_testdemo_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EditTagRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_testdemo_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TagData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_testdemo_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Operator); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_testdemo_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Marketer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_testdemo_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WxUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_testdemo_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MemberUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_testdemo_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PageInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_testdemo_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImageData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_testdemo_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_testdemo_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_testdemo_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MetaRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_testdemo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_testdemo_proto_goTypes,
		DependencyIndexes: file_testdemo_proto_depIdxs,
		MessageInfos:      file_testdemo_proto_msgTypes,
	}.Build()
	File_testdemo_proto = out.File
	file_testdemo_proto_rawDesc = nil
	file_testdemo_proto_goTypes = nil
	file_testdemo_proto_depIdxs = nil
}
