// Code generated by goctl. DO NOT EDIT!
// Source: testdemo.proto

package testdemoclient

import (
	"context"

	"testdemo/testdemo"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	DelTagReq      = testdemo.DelTagReq
	DelTagRes      = testdemo.DelTagRes
	EditTagReq     = testdemo.EditTagReq
	EditTagRes     = testdemo.EditTagRes
	GetTagListData = testdemo.GetTagListData
	GetTagListReq  = testdemo.GetTagListReq
	GetTagListRes  = testdemo.GetTagListRes
	GetTagReq      = testdemo.GetTagReq
	GetTagRes      = testdemo.GetTagRes
	ImageData      = testdemo.ImageData
	Marketer       = testdemo.Marketer
	MemberUser     = testdemo.MemberUser
	MetaRes        = testdemo.MetaRes
	Operator       = testdemo.Operator
	PageInfo       = testdemo.PageInfo
	PingReq        = testdemo.PingReq
	PingRes        = testdemo.PingRes
	TagData        = testdemo.TagData
	WxUser         = testdemo.WxUser

	Testdemo interface {
		Ping(ctx context.Context, in *PingReq, opts ...grpc.CallOption) (*PingRes, error)
		EditTag(ctx context.Context, in *EditTagReq, opts ...grpc.CallOption) (*EditTagRes, error)
		GetTagDetail(ctx context.Context, in *GetTagReq, opts ...grpc.CallOption) (*GetTagRes, error)
		DelTag(ctx context.Context, in *DelTagReq, opts ...grpc.CallOption) (*DelTagRes, error)
		GetTagList(ctx context.Context, in *GetTagReq, opts ...grpc.CallOption) (*GetTagRes, error)
	}

	defaultTestdemo struct {
		cli zrpc.Client
	}
)

func NewTestdemo(cli zrpc.Client) Testdemo {
	return &defaultTestdemo{
		cli: cli,
	}
}

func (m *defaultTestdemo) Ping(ctx context.Context, in *PingReq, opts ...grpc.CallOption) (*PingRes, error) {
	client := testdemo.NewTestdemoClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}

func (m *defaultTestdemo) EditTag(ctx context.Context, in *EditTagReq, opts ...grpc.CallOption) (*EditTagRes, error) {
	client := testdemo.NewTestdemoClient(m.cli.Conn())
	return client.EditTag(ctx, in, opts...)
}

func (m *defaultTestdemo) GetTagDetail(ctx context.Context, in *GetTagReq, opts ...grpc.CallOption) (*GetTagRes, error) {
	client := testdemo.NewTestdemoClient(m.cli.Conn())
	return client.GetTagDetail(ctx, in, opts...)
}

func (m *defaultTestdemo) DelTag(ctx context.Context, in *DelTagReq, opts ...grpc.CallOption) (*DelTagRes, error) {
	client := testdemo.NewTestdemoClient(m.cli.Conn())
	return client.DelTag(ctx, in, opts...)
}

func (m *defaultTestdemo) GetTagList(ctx context.Context, in *GetTagReq, opts ...grpc.CallOption) (*GetTagRes, error) {
	client := testdemo.NewTestdemoClient(m.cli.Conn())
	return client.GetTagList(ctx, in, opts...)
}
