// Code generated by goctl. DO NOT EDIT!
// Source: testdemo.proto

package server

import (
	"context"

	"testdemo/internal/logic"
	"testdemo/internal/svc"
	"testdemo/testdemo"
)

type TestdemoServer struct {
	svcCtx *svc.ServiceContext
	testdemo.UnimplementedTestdemoServer
}

func NewTestdemoServer(svcCtx *svc.ServiceContext) *TestdemoServer {
	return &TestdemoServer{
		svcCtx: svcCtx,
	}
}

func (s *TestdemoServer) Ping(ctx context.Context, in *testdemo.PingReq) (*testdemo.PingRes, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}

func (s *TestdemoServer) EditTag(ctx context.Context, in *testdemo.EditTagReq) (*testdemo.EditTagRes, error) {
	l := logic.NewEditTagLogic(ctx, s.svcCtx)
	return l.EditTag(in)
}

func (s *TestdemoServer) GetTagDetail(ctx context.Context, in *testdemo.GetTagReq) (*testdemo.GetTagRes, error) {
	l := logic.NewGetTagDetailLogic(ctx, s.svcCtx)
	return l.GetTagDetail(in)
}

func (s *TestdemoServer) DelTag(ctx context.Context, in *testdemo.DelTagReq) (*testdemo.DelTagRes, error) {
	l := logic.NewDelTagLogic(ctx, s.svcCtx)
	return l.DelTag(in)
}

func (s *TestdemoServer) GetTagList(ctx context.Context, in *testdemo.GetTagReq) (*testdemo.GetTagRes, error) {
	l := logic.NewGetTagListLogic(ctx, s.svcCtx)
	return l.GetTagList(in)
}
